/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "wxs_constants.h"



const wxsConstants g_wxs_constants;

wxsConstants::wxsConstants() {
}



