/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef wxs_CONSTANTS_H
#define wxs_CONSTANTS_H

#include "wxs_types.h"



class wxsConstants {
 public:
  wxsConstants();

};

extern const wxsConstants g_wxs_constants;



#endif
